# Generated by Django 3.0.2 on 2020-01-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=300)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
